CREATE TABLE crunch (
    mlb_id TEXT
  , mlb_name TEXT
  , mlb_pos TEXT
  , mlb_team TEXT
  , mlb_team_long TEXT
  , bats TEXT
  , throws TEXT
  , birth_year TEXT
  , bp_id TEXT
  , bref_id TEXT
  , bref_name TEXT
  , cbs_id TEXT
  , cbs_name TEXT
  , cbs_pos TEXT
  , espn_id TEXT
  , espn_name TEXT
  , espn_pos TEXT
  , fg_id TEXT
  , fg_name TEXT
  , fg_pos TEXT
  , lahman_id TEXT
  , nfbc_id TEXT
  , nfbc_name TEXT
  , nfbc_pos TEXT
  , retro_id TEXT
  , retro_name TEXT
  , debut TEXT
  , yahoo_id TEXT
  , yahoo_name TEXT
  , yahoo_pos TEXT
  , mlb_depth TEXT
  , ottoneu_id TEXT
  , ottoneu_name TEXT
  , ottoneu_pos TEXT
  , rotowire_id TEXT
  , rotowire_name TEXT
  , rotowire_pos TEXT
);
